name: "📛📛 Name of PR"
about: "This PR fixes #NUMBER_OF_THE_ISSUE, and fixes #NUMBER_OF_THE_ISSUE"
title: ""
body:
  - type: markdown
    attributes:
      value: |
        # **Name of PR**
  - input: textarea
    id: description
    attributes:
      label: "Description"
      description: "Please include a summary of the change and/or which issue is fixed."
      required: true
  - input: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context or additional information about the pull request."

