name: "🐞 Bug Report"
description: "Report an issue to help the project improve."
title: "[Bug] "
labels: ["bug"]
body:
    - type: markdown
      attributes:
          value: |
              # **🐞 Bug Report**
    - type: textarea
      attributes:
        label: "Bug Description"
        description: "Please provide a clear and concise description of what the bug is."
        required: true
    - type: textarea
      attributes:
        label: "Steps to Reproduce"
        description: "Write the steps here (add or remove as many steps as needed)"
        placeholder: |
            1.
            2.
            3.
            4.
        required: true
    - type: textarea
      attributes:
        label: "Additional Context"
        description: "Add any other context or additional information about the problem here."
        required: false
