name: "💉 Test"
about: "Creation tests."
title: "[Test] "
labels: ["test"]
body:
  - type: markdown
    attributes:
      value: |
        # **💉 Creation Test**
  - type: textarea
    id: test
    attributes:
      label: "Which jobs/test(s) is needed to be created"
      description: "The CI jobs or tests that need to be created"
      required: true
  - type: textarea
    id: additional-context
    attributes:
      label: "Additional context"
      description: "Add any other context or additional information about the problem here."

