name: "🚀🆕 Feature Request"
about: "Suggest an idea or possible new feature for this project."
title: "[Feature] "
labels: ["feature"]
body:
  - type: markdown
    attributes:
        value: |
            # **🚀 Feature Request**
  - type: textarea
    id: feature
    attributes:
        label: "Describe the feature."
        description: "A clear and concise description of what the feature is."
        required: true
  - type: textarea
    id: solution
    attributes:
        label: "Describe the solution you'd like"
        description: "A clear and concise description of what you want to happen."
        required: false


