name: Generated APK AAB (Upload - Create Artifact To Github Action)

env:
  main_project_module: app

on:
  push:
    branches:
      - '**'

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set current date as env variable
        run: echo "date_today=$(date +'%Y-%m-%d')" >> $GITHUB_ENV

      - name: Set repository name as env variable
        run: echo "repository_name=$(echo '${{ github.repository }}' | awk -F '/' '{print $2}')" >> $GITHUB_ENV

      - name: Set Up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'
          cache: 'gradle'

      - name: Change wrapper permissions
        run: chmod +x ./gradlew

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install SDK packages
        run: |
          sdkmanager "platform-tools" "platforms;android-33" "build-tools;33.0.0" "system-images;android-33;google_apis;x86_64" "emulator"

      - name: Add Android SDK to PATH
        run: echo "export PATH=$PATH:/usr/local/lib/android/sdk/emulator" >> $GITHUB_ENV

      - name: Verify emulator installation
        run: ls -l /usr/local/lib/android/sdk/emulator

      - name: Set permissions for emulator
        run: chmod +x /usr/local/lib/android/sdk/emulator/emulator

      - name: List available AVDs
        run: avdmanager list avds

      - name: Create and start an emulator
        run: |
          echo "no" | /usr/local/lib/android/sdk/tools/bin/avdmanager create avd -n test -k "system-images;android-33;google_apis;x86_64" --sdcard 512M --force
          nohup /usr/local/lib/android/sdk/emulator/emulator -avd test -no-accel -no-audio -no-window &

      - name: Wait for emulator to boot
        run: |
          adb devices
          for i in {1..10}; do
            adb wait-for-device
            if [ $? -eq 0 ]; then
              adb shell input keyevent 82
              break
            fi
            sleep 30
          done

      - name: Run gradle tests
        run: ./gradlew connectedDebugAndroidTest

      - name: Build gradle project
        run: ./gradlew build

      - name: Build apk debug project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assembleDebug

      - name: Build apk release project (APK) - ${{ env.main_project_module }} module
        run: ./gradlew assemble

      - name: Build app bundle release (AAB) - ${{ env.main_project_module }} module
        run: ./gradlew ${{ env.main_project_module }}:bundleRelease

      - name: Upload APK Debug - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK(s) debug generated
          path: ${{ env.main_project_module }}/build/outputs/apk/debug/

      - name: Upload APK Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - APK(s) release generated
          path: ${{ env.main_project_module }}/build/outputs/apk/release/

      - name: Upload AAB (App Bundle) Release - ${{ env.repository_name }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.date_today }} - ${{ env.repository_name }} - App bundle(s) AAB release generated
          path: ${{ env.main_project_module }}/build/outputs/bundle/release/







